---
- name: Check OS Server Health
  hosts: all
  remote_user: jenkins
  tasks:
    - name: Check server uptime
      shell: uptime
      register: server_uptime

    - name: Check memory usage
      shell: free -m
      register: memory_usage

    - name: Display results
      debug:
        msg: "Server uptime: {{ server_uptime.stdout }} | Memory usage: {{ memory_usage.stdout }}"
...
